### ISSUE TITLE
Markup for messages starting with mentions is broken for me

### ISSUE THREAD

**Issue by Happy0** [stripedpajamas/stool#33]
For example, this is the raw message Lance sent to me:

```
{
  "key": "%GB/67vwA+ZOU9E1zBKnd66BIW84t1YSTUIgXnnm9xvM=.sha256",
  "value": {
    "previous": "%9KydQF48RH/m6zR9ChRodSKMAPZdThOYjM1w0WCtz64=.sha256",
    "sequence": 1404,
    "author": "@W87GwaaxNj0PSBbtc5qUm/A/xOO8AWPdNtJn6hzR8s0=.ed25519",
    "timestamp": 1538659984858,
    "hash": "sha256",
    "content": {
      "type": "scat_message",
      "text": "@happy0at this stage yes... I'm away for two weeks, and only get back that week so I might be wrecked. :sleepy:"
    },
    "signature": "Rz+0nnQ0E1ucihu+7bh81mFSQtQK29YArnFrSfishtYbundYfWBe2qKUZUcYrcSO7sLulJl0KQl75zpUMZ/9Bg==.sig.ed25519"
  }
}
```

This is how it was rendered:

Text: `[@happy0]{.mention😪`

Screenshot:

![2018-10-04-150338_1600x900_scrot](https://user-images.githubusercontent.com/1145180/46479375-cff2c700-c7e6-11e8-957e-0355efd45546.png)

**Comment by stripedpajamas** [comment]
So sad 😢 

The markdown rendering piece of gester is very janky. I will investigate. Thanks for the heads up @Happy0

**Comment by Happy0** [comment]
No problem. Thanks for a great scuttlebutt chat client, btw :)

**Comment by stripedpajamas** [comment]
@Happy0 can you pull down master and see if that mention rendering bug is fixed? I just merged in a potential fix from @korlando7
