### ISSUE TITLE
Initial message data from new ssb user causes Gester to load very slowly on startup

### ISSUE THREAD

**Issue by ghost** [stripedpajamas/stool#38]
When someone becomes a new ssb user they download every public ssb chat that has ever been sent. Since Gester loads the last 2 weeks of downloaded data and this new user has downloaded all of the messages within the last 2 weeks, this causes all existing public messages to be rendered on startup. This makes Gester very laggy and takes a few minutes to get to a useable state.

The best fix for this would be to change how Gester decides what messages to load. If we could find a way to pull the messages that have been **sent** in the last 2 weeks instead of downloaded in the last 2 weeks, that would be a great fix.

Now, as ssb grows, if 2 weeks of public chats sent increases to an amount close to the number of all public chats now, we will start to see this problem again. A long term fix would be rendering a max number of messages on startup and having the option to load more on scroll up.

**Comment by stripedpajamas** [comment]
Fixed upstream https://github.com/stripedpajamas/ssb-chat-core/commit/740f06a89861e18e9d189b2ed3ae08e568b0dddf

**Comment by stripedpajamas** [comment]
Updated deps in #39
